services:
  conta-read:
    container_name: bantads-contaread
    image: postgres
    environment:
      POSTGRES_USER: bantads
      POSTGRES_PASSWORD: 123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - postgres
    restart: unless-stopped
    
  conta-cud:
    container_name: bantads-contacud
    image: postgres
    environment:
      POSTGRES_USER: bantads
      POSTGRES_PASSWORD: 123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5437:5432"
    networks:
      - postgres
    restart: unless-stopped  

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-conta'
    ports:
      - 5674:5672
      - 15674:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq

networks:
  rabbitmq:
    driver: bridge
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  rabbitmq: